repos:

- hooks:
  - id: hadolint
    name: for alpine 3.13
    args:
      - alpine3.13.Dockerfile
  - id: hadolint
    name: for alpine 3.14
    args:
      - alpine3.14.Dockerfile
  repo: https://github.com/hadolint/hadolint
  rev: v2.10.0

- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.24.0
