name: Publish Docker image

on:
  push:
    branches:
      - 'main'

jobs:
  push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build and push Docker images 8.0.13 for Alpine 3.13
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: hashman/nginx-php-fpm
          registry: docker.io
          dockerfile: alpine3.13.Dockerfile
          buildArgs: PHP_VER=8.0.13
          tags: 8.0.13-alpine3.13, 8.0.13.0-alpine3.13
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images 8.0.13 for Alpine 3.14
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: hashman/nginx-php-fpm
          registry: docker.io
          dockerfile: alpine3.14.Dockerfile
          buildArgs: PHP_VER=8.0.13
          tags: 8.0.13-alpine3.14, 8.0.13.0-alpine3.14
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
